export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT = "LOGOUT";

export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";

export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const FETCH_EVENTS = "FETCH_EVENTS";

export const ADD_EVENTS_FAILURE = "ADD_EVENTS_FAILURE";
export const ADD_EVENTS = "ADD_EVENTS";

export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
export const DELETE_EVENT = "DELETE_EVENT";

export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_FRIENDS_FAILURE = "FETCH_FRIENDS_FAILURE";
export const FETCH_FRIENDS = "FETCH_FRIENDS";

export const ADD_FRIEND_FAILURE = "ADD_FRIEND_FAILURE";
export const ADD_FRIEND = "ADD_FRIEND";

export const DELETE_FRIEND_FAILURE = "DELETE_FRIEND_FAILURE";
export const DELETE_FRIEND = "DELETE_FRIEND";

export const FETCH_MY_FRIENDS_SUCCESS = "FETCH_MY_FRIENDS_SUCCESS";
export const FETCH_MY_FRIENDS_FAILURE = "FETCH_MY_FRIENDS_FAILURE";
export const FETCH_MY_FRIENDS = "FETCH_MY_FRIENDS";

export const FETCH_FRIENDS_EVENTS_SUCCESS = "FETCH_FRIENDS_EVENTS_SUCCESS";
export const FETCH_FRIENDS_EVENTS_FAILURE = "FETCH_FRIENDS_EVENTS_FAILURE";
export const FETCH_FRIENDS_EVENTS = "FETCH_FRIENDS_EVENTS";