export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT = "LOGOUT";

export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";

export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const FETCH_EVENTS = "FETCH_EVENTS";

export const ADD_EVENTS_FAILURE = "ADD_EVENTS_FAILURE";
export const ADD_EVENTS = "ADD_EVENTS";

export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
export const DELETE_EVENT = "DELETE_EVENT";